
export const ACTION_NOTES_FETCH_ALL ='ACTION_NOTES_FETCH_ALL';
export const ACTION_NOTES_SEARCH ='ACTION_NOTES_SEARCH';
export const ACTION_NOTE_BY_ID ='ACTION_NOTE_BY_ID';
export const ACTION_NOTE_DELETE ='ACTION_NOTE_DELETE';
export const ACTION_NOTE_EDIT ='ACTION_NOTE_EDIT';
export const ACTION_NOTE_SELECT ='ACTION_NOTE_SELECT';


export const ACTION_USER_SIGNIN ='ACTION_USER_SIGNIN';
export const ACTION_USER_SIGNOUT ='ACTION_USER_SIGNOUT';

export const ACTION_SELECT_MODE ='ACTION_SELECT_MODE';









export{}